# Version
version: '3.1'

# Setup
services:

  # PHP
  php:
    depends_on:
      - db
    image: Docker
    restart: always
    ports:
      - 5000:80
    volumes:
      - ./application/public:/var/www/html

  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PMA_HOST: db

  # MySQL
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - data_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: absen
      MYSQL_PASSWORD: j45m1tDB
      MYSQL_ROOT_PASSWORD: j45m1tDB
# Volumes
volumes:
  data_db:
  data_uploads: